#---- Thorium -----------------------------
windowrulev2 = workspace 5 silent, title:^.*(Thorium)$

#---- JetBrains ---------------------------
windowrulev2 = workspace 6 silent, class:^(jetbrains-.*)$
windowrulev2 = nodim, class:^(jetbrains-.*)$
windowrulev2 = forceinput, class:^(jetbrains-.*)$
windowrulev2 = windowdance, class:^(jetbrains-.*)$

windowrulev2 = center, class:^(jetbrains-toolbox.*)$
windowrulev2 = float, class:^(jetbrains-toolbox.*)$


#---- Kitty -------------------------------
windowrulev2 = float, class:(kitty)
windowrulev2 = noinitialfocus, class:(kitty)

#---- Nemo --------------------------------
windowrulev2 = float, class:(nemo)


#---- xreader -----------------------------
windowrulev2 = float, title:(Document Viewer)


#---- Wi-Fi menu --------------------------
windowrulev2 = move 2 25, class:(kitty),title:(nmtui)

#---- Bluetooth menu ----------------------
windowrulev2 = size 885 200, class:(kitty), title:(bluetuith)
windowrulev2 = move 2 25, class:(kitty), title:(bluetuith)


#---- polkit-kde-authentication-agent -----
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$

#---- xwaylandvideobridge -----------------
windowrulev2 = opacity 0.0 override 0.0 override, class:^(xwaylandvideobridge)$
windowrulev2 = noanim, class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 100 100, class:^(xwaylandvideobridge)$
windowrulev2 = noblur, class:^(xwaylandvideobridge)$
